/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColumnSet: typeof import('./components/ElementUI/TTable/ColumnSet.vue')['default']
    EditCell: typeof import('./components/ElementUI/TEditTable/EditCell.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCard: typeof import('element-ui/lib/card')['default']
    ElCheckbox: typeof import('element-ui/lib/checkbox')['default']
    ElCheckboxGroup: typeof import('element-ui/lib/checkbox-group')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElPagination: typeof import('element-ui/lib/pagination')['default']
    ElPopover: typeof import('element-ui/lib/popover')['default']
    ElRadio: typeof import('element-ui/lib/radio')['default']
    ElRow: typeof import('element-ui/lib/row')['default']
    ElSelect: typeof import('element-ui/lib/select')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElTable: typeof import('element-ui/lib/table')['default']
    ElTableColumn: typeof import('element-ui/lib/table-column')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    MoreChoose: typeof import('./components/ElementUI/TQueryCondition/moreChoose.vue')['default']
    OptComponent: typeof import('./components/ElementUI/TQueryCondition/OptComponent.vue')['default']
    RenderCol: typeof import('./components/ElementUI/TTable/renderCol.vue')['default']
    RenderComp: typeof import('./components/ElementUI/TQueryCondition/renderComp.vue')['default']
    RenderHeader: typeof import('./components/ElementUI/TTable/renderHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleEdit: typeof import('./components/ElementUI/TTable/singleEdit.vue')['default']
    SingleEditCell: typeof import('./components/ElementUI/TTable/singleEditCell.vue')['default']
    TButton: typeof import('./components/ElementUI/TButton.vue')['default']
    TEditTable: typeof import('./components/ElementUI/TEditTable/index.vue')['default']
    TInput: typeof import('./components/ElementUI/TInput.vue')['default']
    TLayoutPage: typeof import('./components/ElementUI/TLayoutPage.vue')['default']
    TLayoutPageItem: typeof import('./components/ElementUI/TLayoutPageItem.vue')['default']
    TQueryCondition: typeof import('./components/ElementUI/TQueryCondition/index.vue')['default']
    TTable: typeof import('./components/ElementUI/TTable/index.vue')['default']
    TTableColumn: typeof import('./components/ElementUI/TTable/TTableColumn.vue')['default']
    TTimerBtn: typeof import('./components/ElementUI/TTimerBtn.vue')['default']
  }
}
